version: '3.8'

services:
  script-runner:
    build: .
    depends_on:
      - sqlite-db
    volumes:
      - ./data:/data
      - ./schema.sql:/app/schema.sql
      - ./create_db.py:/app/create_db.py
      - ./insert_data.py:/app/insert_data.py
      - ./magasins.csv:/app/magasins.csv
      - ./produits.csv:/app/produits.csv
      - ./ventes.csv:/app/ventes.csv
    environment:
      - DB_PATH=/data/sales.db
    restart: "no"  # Add this to prevent automatic restarts

  sqlite-db:
    image: alpine:latest
    platform: linux/amd64
    stdin_open: true
    tty: true
    volumes:
      - ./data:/data
    command: sh -c "apk add --no-cache sqlite && tail -f /dev/null"